### ISSUE TITLE
The menu to move the camera do nothing

### ISSUE THREAD

**Issue by marcoKoH2** [GilesBathgate/RapCAD#10]
in ubuntu version 0.9.7~trusty1
the entries menu View -> Top Bottom Left Right Front Back and shortcuts Ctrl+[4-9]
do nothing.

**Comment by GilesBathgate** [comment]
fixed in 6b7b194e9eeb873c0a2b98c386527a3a6457092b

**Comment by marcoKoH2** [comment]
thanks very fast !
I've to compile of my (I've middle knowledges)
or I can wait (1-2 week)
a new release on your repo ?
thanks again

**Comment by GilesBathgate** [comment]
You can use a snapshot version (rapcad - 0.9.7+1SNAPSHOT20151125~trusty1) by adding ppa:gilesbathgate/rapcad-snapshot to your system's Software Sources.

**Comment by marcoKoH2** [comment]
I've just finish to compile to myself using QtCreator (rapcad.pro)
all works fine, thanks again.

**Comment by GilesBathgate** [comment]
(Since github have removed the private messaging feature I will post here, which is not ideal)

How did you get on with RapCAD in general, were you able to do what you wanted? Did you find any other missing features or bugs that you really want fixed, or implemented?
