### ISSUE TITLE
what's the difference between rapcad and openscad?

### ISSUE THREAD

**Issue by yunfan** [GilesBathgate/RapCAD#13]
it looks like both share the same language and same ui

**Comment by GilesBathgate** [comment]
Here is a feature matrix https://github.com/GilesBathgate/RapCAD/blob/master/doc/feature_matrix.asciidoc (It might not be totally up to date)

**Comment by yunfan** [comment]
ok i got it, so its a fork and improve?

**Comment by GilesBathgate** [comment]
Yes, if you would call re-written from scratch a fork.

**Comment by yunfan** [comment]
ok
