### ISSUE TITLE
Add icon to app on macOS

### ISSUE THREAD

**Issue by ajmas** [GilesBathgate/RapCAD#17]
The app generated on macOS is only using the generic icon and not the RapCAD icon.

 - The icon can be added per: https://doc.qt.io/qt-5/appicon.html
 - A `rapcad.icns` file will need to be generated, though this will require the addition of larger icons, per: https://stackoverflow.com/questions/12306223/how-to-manually-create-icns-files-using-iconutil

**Comment by ajmas** [comment]
@GilesBathgate do you have original vector images for the icon?

**Comment by GilesBathgate** [comment]
There is a big version of the icon in help/about:

![image](https://user-images.githubusercontent.com/444143/73547373-b1322e00-4436-11ea-8122-75141596f37e.png)
Does that help?

**Comment by ajmas** [comment]
Thanks. Will follow the instructions here for the icons:

https://elliotekj.com/2014/05/27/how-to-create-high-resolution-icns-files

Won't  include the @2x, since I am not sure about the finer details

**Comment by GilesBathgate** [comment]
There is no need to duplicate the icon files

```
giles@BPEU0197:~/projects/rapcad/icons$ fdupes . -r
./rapcad-32x32.png                      
./Appicon.iconset/icon_32x32.png

./rapcad-16x16.png
./Appicon.iconset/icon_16x16.png

./rapcad-64x64.png
./Appicon.iconset/icon_64x64.png
```

You can just symlink them.

**Comment by ajmas** [comment]
ok. which direction would you want the symlink to go?

./Appicon.iconset/icon_32x32.png -> ./icon_32x32.png

or 

./icon_32x32.png -> ./Appicon.iconset/icon_32x32.png

**Comment by GilesBathgate** [comment]
e.g: `ln -s ../rapcad-32x32.png icon_32x32.png`

**Comment by GilesBathgate** [comment]
Can you also paste a screenshot of what the icon looks like on your mac to give me an idea.

**Comment by ajmas** [comment]
Here is the screenshot. Just trying to see if the iconutil likes symlinks

<img width="420" alt="Screenshot 2020-02-08 at 16 25 10" src="https://user-images.githubusercontent.com/682269/74091610-ab1ffb00-4a8f-11ea-8014-2ac5b3d16655.png">

**Comment by GilesBathgate** [comment]
>Just trying to see if the iconutil likes symlinks

If not do them the other way, not really fussed.

**Comment by ajmas** [comment]
Ok, resolved. Let me know if those changes are fine?

**Comment by GilesBathgate** [comment]
LGTM.

**Comment by GilesBathgate** [comment]
hrm, on my machine the symlinks appear broken, this is due to the link using Camel case directory name `AppIcon.iconset`, but the folder being `Appicon.iconset`  you should be able to fix with `git mv Appicon.iconset AppIcon.iconset`

**Comment by ajmas** [comment]
Just trying to fix this. hopefully the last push fixes this. missed that since my machine is case-insenstive
