### ISSUE TITLE
CGAL assertion violation when importing STL

### ISSUE THREAD

**Issue by iamwilhelm** [GilesBathgate/RapCAD#2]
I have three files in the same directory: trunk.scad, current.scad, and imported.scad

### trunk.scad

~~~
module trunk() {
  cylinder(h=20, r = 10);
}

trunk();
~~~

### current.scad

~~~
include <trunk.scad>

union() {
  translate([0, 0, 30]) sphere(15);
  trunk();
}
~~~

### imported.scad

~~~
import <current.stl> as current;

current();
~~~

I export current to stl using: "rapcad -o current.stl current.scad" That goes fine. But then when I "rapcad -o imported.stl imported.scad", it failes with:

~~~
Info: Importing '/Users/iamwil/Dropbox/projects/designs/contrib/oneofthesethings/src/current.stl'

What: CGAL ERROR: assertion violation!
Expr: check_protocoll == 0
File: /opt/local/include/CGAL/Polyhedron_incremental_builder_3.h
Line: 198
Warning: No top level object.
Total rendering time: 0m 0s 65ms.
~~~

I've seen a different CGAL assertion violation here before as well. I believe this is a bug, unless I'm doing something egregiously wrong.

**Comment by GilesBathgate** [comment]
This now works if you export the STL with an output precision set to 6 and use function rounding (tested in RapCAD 0.9.7)
