### ISSUE TITLE
Updates and feature requests

### ISSUE THREAD

**Issue by WillAdams** [GilesBathgate/RapCAD#23]
Please create /r/rapcad on reddit

**Comment by GilesBathgate** [comment]
Great idea's @WillAdams But can you separate these into separate feature requests, and edit this one to be just the request to create `/r/rapcad`

Incidentally, I need to wait 30 days and have karma before I can create a subreddit.

**Comment by WillAdams** [comment]
If you wish, I can create it, then add you as a moderator to /r/rapcad

**Comment by GilesBathgate** [comment]
I should think that will work.

**Comment by GilesBathgate** [comment]
Its u/GilesBathgate

**Comment by WillAdams** [comment]
I've sent you an invite to be a moderator.

**Comment by GilesBathgate** [comment]
Thanks.
