### ISSUE TITLE
Unicode files not handled properly?

### ISSUE THREAD

**Issue by WillAdams** [GilesBathgate/RapCAD#27]
If you export an OpenSCAD file from Blockscad, then change the file extension to .rcad and double-click on it (after associating .rcad files with RapCAD), when it opens the BOM is viewable as text so one gets:

ï»¿//!OpenSCAD

rather than 

//!OpenSCAD

**Comment by GilesBathgate** [comment]
>The Unicode Standard permits the BOM in UTF-8, but does not require or recommend its use.

That said I can understand why it's convenient to have the parser detect and ignore it, so I will add something to the lexer/parser to handle this.

**Comment by GilesBathgate** [comment]
Fixed in 43b67ee7dd096f3a6d68a40318d8e65c602c0a4d
