### ISSUE TITLE
Summary for curated list of code CAD

### ISSUE THREAD

**Issue by Irev-Dev** [GilesBathgate/RapCAD#35]
Hey Giles 👋 ,

I finally got around to putting together a list of all of the code-CAD projects that I know of [here](https://kurthutten.com/blog/curated-code-cad), and also on [Github](https://github.com/Irev-Dev/curated-code-cad).

I've put a short summary of each one, but it's hard to do them all justice. for RapCAD I've only got:
Another project inspired by OpenScad.

If you would like to give me a summary of the project, and perhaps some points of how it differs from other similar projects would be happy to include it. I think max three paragraphs would be about right. Open a PR on reply to this issue and I'll include it.

**Comment by GilesBathgate** [comment]
I consider the key differences to be procedural vs functional programming language style, (i.e variables can be modified) and the use of arbitrary precision arithmetic throughout (meaning there are no unexpected double/float rounding errors).

There is also a [feature matrix](https://github.com/GilesBathgate/RapCAD/blob/master/doc/feature_matrix.asciidoc)

**Comment by Irev-Dev** [comment]
Thanks Giles.

**Comment by GilesBathgate** [comment]
@Irev-Dev Any chance you can change your screenshot. 

This is Slic3r

![image](https://user-images.githubusercontent.com/444143/97801526-474cec00-1c35-11eb-915b-265c4b43549b.png)

This is RapCAD:

![image](https://user-images.githubusercontent.com/444143/97801540-677cab00-1c35-11eb-953c-3654c28b6ab1.png)

**Comment by Irev-Dev** [comment]
@GilesBathgate  Oh sorry,
Clearly was absent minded when I did that.
Should be fixed now.

Let me know if there's anything else I can doy.

**Comment by Irev-Dev** [comment]
Me again.

I also want to add some of the best real-world examples of Code-CAD being used out in the wild. Do you know of any good projects using RapCAD that I can feature?

So far what I've found is:
- [Acedemics using it for reactor design](https://github.com/ukaea/paramak)
- [Lego compatible blocks](https://fxbricks.com/)
- [specialised in-house equipment for drones](https://twitter.com/robsmallshire/status/1343477584458346497)
- [Pruse 3d printer](https://github.com/prusa3d/Original-Prusa-i3)

**Comment by GilesBathgate** [comment]
I don't know of anyone specifically using RapCAD for their project instead of Openscad. There is a list of some notable ones here: https://www.openscad.org/gallery.html
