### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by ajmas** [GilesBathgate/RapCAD#36]
GitHub now provides a means to do continuous integration, by means of workflows, so it could be interesting to start using this for building the project. 

One explanation, targeting macOS:

https://rhonabwy.com/2020/05/09/continuous-integration-with-github-actions-for-macos-and-ios-projects/

Targets would be: Linux, Windows and macOS.

If anyone wants to take up the challenge, you are welcome.

**Comment by GilesBathgate** [comment]
@ajmas I already build macOS releases using TravisCI

**Comment by ajmas** [comment]
@GilesBathgate I hadn't noticed. I see the config file now. Is Windows and Linux target too?

**Comment by GilesBathgate** [comment]
Windows releases are built using Appveyor, and Linux Releases are built using PPA. It might be worth streamlining this in future using Github CI, but it's not a priority at this time.

**Comment by GilesBathgate** [comment]
This seems to be a good idea as travis-ci have changed their pricing model.

**Comment by ajmas** [comment]
I did some work for macOS for another project, but unfortunately the resulting binaries appear corrupt and I haven’t had time to investigate why. I am sharing it here to see if it helps, despite the current state:

https://github.com/ajmas/Boxer/tree/workflow-tweaking

**Comment by GilesBathgate** [comment]
Continuous integration is now active.
