### ISSUE TITLE
Should include work in directories other than the current one?

### ISSUE THREAD

**Issue by WillAdams** [GilesBathgate/RapCAD#39]
It's not listed in:

file:///C:/Program%20Files/RapCAD/user_guide.html

but it highlights in the program:

When using OpenSCAD I have library files in:

C:\Users\willa\OneDrive\Documents\OpenSCAD\libraries

and tried:

C:\Users\willa\OneDrive\Documents\RapCAD\Libraries\

but no joy, it seems to only search in the current directory.

The error message is:

    Я: Can't open input file 'C:/Users/willa/Desktop/gcodepreview.scad'
    Line 1: syntax error at character 0: ''
    Warning: no top level object.
    Я: 

when it can't find the file, but when the file is there to be loaded we get:

    Line 3: syntax error at character 1: ';'
    Warning: no top level object.
    Я: 

for the test file:

    include <gcodepreview.scad>;

    cylinder(1,2,3,center=false);
    writeln("Text");

**Comment by GilesBathgate** [comment]
@WillAdams the `\` character is an escape character, you will have to either use `\\` or `\` 
e.g: `C:\\Users\\willa\\OneDrive\\Documents\\OpenSCAD\\libraries`
or: `C:/Users/willa/OneDrive/Documents/OpenSCAD/libraries`

**Comment by WillAdams** [comment]
Thanks! All fixed!

Would it be desirable to load from a fixed location such as Documents/RapCAD/Libraries  ?

**Comment by GilesBathgate** [comment]
>load from a fixed location such as Documents/RapCAD/Libraries

@WillAdams Sorry I hit close too soon, please open a new issue for this anyway.
