### ISSUE TITLE
Add support for OpenSCAD CLI options, esp. "viewall"

### ISSUE THREAD

**Issue by WillAdams** [GilesBathgate/RapCAD#45]
Using the nifty new OpenSCAD Graph Editor: https://github.com/derkork/openscad-graph-editor

but it calls OpenSCAD using a command-line option "viewall" which results in an error when calling rapcad.exe:

![image](https://user-images.githubusercontent.com/3543154/184493733-5cef3873-f394-4d84-acdc-c27bac6a74e5.png)

List of the options at:

https://en.m.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_OpenSCAD_in_a_command_line_environment

Having a superset of the OpenSCAD options would help interoperability a lot.

**Comment by GilesBathgate** [comment]
I can quickly add a viewall option so it doesn't error. Getting it to fit the view might take a little longer. Do you want me to just ward off the error or can you wait for the full feature?

**Comment by WillAdams** [comment]
Just warding off the error would be great!

The full feature support would be gravy, but I can wait for that. 

Thanks!

**Comment by GilesBathgate** [comment]
@WillAdams you can test a Windows snapshot if you like https://github.com/GilesBathgate/RapCAD/suites/7805119228/artifacts/329357650

**Comment by WillAdams** [comment]
Thanks! This is working great!

![image](https://user-images.githubusercontent.com/3543154/188542870-d6f5f146-f7c3-48df-af54-d8005d818071.png)

**Comment by GilesBathgate** [comment]
Fixed
