### ISSUE TITLE
Second long comment causes syntax error

### ISSUE THREAD

**Issue by WillAdams** [GilesBathgate/RapCAD#46]
The file:

    /**
     * 
     * 
     */
    module Top_Bottom() {
        
        cube(size = [Width, Depth, Stock_Thickness]);
    }
    
    /**
     * 
     * 
     */
    module Sides() {
        
        cube(size = [Height, Depth, Stock_Thickness]);
    }
    
    Height = 50;
    Width = 210;
    Depth = 300;
    Stock_Thickness = 6;
    Top_Bottom();
    translate(v = [0, 0, (Height - Stock_Thickness)]) {
        Top_Bottom();
    }

    rotate(v = [0, 0, 0], a = 90) {
        Sides();
    }

Has the following error for line 10:

    syntax error at character 1: "/"

The file works fine in OpenSCAD.

**Comment by GilesBathgate** [comment]
Fixed in 247a37d9bc21a041c86d7fd0b2981c657c8dbac6
