### ISSUE TITLE
Broken Manual Link

### ISSUE THREAD

**Issue by codazoda** [GilesBathgate/RapCAD#49]
The link to the manual on the User Guide seems to be broken. The link is in the first paragraph at the URL below.

https://github.com/GilesBathgate/RapCAD/blob/master/doc/user_guide.asciidoc

I'd fix this, and send a PR, but I'm not sure if there's a plan to compile this manual somehow. The manual icon in RapCAD currently links directly to this file on GitHub. A quick fix from `link:manual.html` to `link:manual.asciidoc` would probably fix it in the source file as presented on GitHub but might break something in a compiled version.

**Comment by GilesBathgate** [comment]
https://github.com/GilesBathgate/RapCAD/issues/48#issuecomment-1624885472

Regarding the manual url, it only works when the documentation is compiled, the asciidoc file becomes an html file.
The source for the manual is here: https://github.com/GilesBathgate/RapCAD/blob/master/doc/manual.asciidoc
