### ISSUE TITLE
Customize print area and base

### ISSUE THREAD

**Issue by nichtich** [GilesBathgate/RapCAD#5]
Size of the print area and base should not be hard-coded in `glview.cpp` but customizable in `preferences.cpp`. I think it best to allow for setting the values by hand and to select from a list of common settings for known 3D printers.

**Comment by GilesBathgate** [comment]
Implemented in commits fa0d7370c41b51073e6cf4d4db6029a56fde5318 , 4f60589f53722245cfe0f0ba3fc61741aa9320d9 and 103457c08526e71211a10407d24f05a9534c81d0

Currently 2 "common settings" are the Prusa Mk42 heated bed, and the Prusa Mk2 heated bed. The volume and print origin can be configured by hand.
