### ISSUE TITLE
STL export fails to export sliced or flat objects

### ISSUE THREAD

**Issue by mildred** [GilesBathgate/RapCAD#7]
Take the following object:

```
slice(0) translate([0, 0, -30]){
  cylinder(60, 10, center=true);
}
```

Or this one:

```
square(40);
```

The STL export result in an almost empty file:

```
solid RapCAD_Model
endsolid RapCAD_Model
```

It should be possible to export flat geometry. This would make RapCAD a great 2D geometry editor.

**Comment by GilesBathgate** [comment]
SVG export Implemented in commit 13db29ddce2f52878cbcb4f88d9671110a93b3d0
